import type {
  Client,
  TravelRequest,
  Booking,
  Invoice,
  Supplier,
  AgencyUser,
  RequestOption,
  RequestMessage,
} from "./types";

export const mockUsers: AgencyUser[] = [
  {
    id: "u1",
    agency_id: "ag1",
    name: "Priya Sharma",
    email: "priya@traveledge.in",
    role: "owner",
  },
  {
    id: "u2",
    agency_id: "ag1",
    name: "Arjun Mehta",
    email: "arjun@traveledge.in",
    role: "consultant",
  },
  {
    id: "u3",
    agency_id: "ag1",
    name: "Sneha Kapoor",
    email: "sneha@traveledge.in",
    role: "consultant",
  },
  {
    id: "u4",
    agency_id: "ag1",
    name: "Rahul Nair",
    email: "rahul@traveledge.in",
    role: "accountant",
  },
];

export const mockClients: Client[] = [
  {
    id: "c1",
    agency_id: "ag1",
    company_name: "Infosys Limited",
    contact_name: "Kavitha Reddy",
    contact_email: "kavitha.reddy@infosys.com",
    contact_phone: "+91 98765 43210",
    credit_limit: 2000000,
    credit_days: 30,
    portal_token: "infosys-a8x2k",
    outstanding_balance: 385000,
    total_requests: 47,
  },
  {
    id: "c2",
    agency_id: "ag1",
    company_name: "Wipro Technologies",
    contact_name: "Sanjay Desai",
    contact_email: "sanjay.d@wipro.com",
    contact_phone: "+91 98765 11111",
    credit_limit: 1500000,
    credit_days: 45,
    portal_token: "wipro-b7y3l",
    outstanding_balance: 127500,
    total_requests: 31,
  },
  {
    id: "c3",
    agency_id: "ag1",
    company_name: "Tata Consultancy Services",
    contact_name: "Meena Iyer",
    contact_email: "meena.iyer@tcs.com",
    contact_phone: "+91 98900 22222",
    credit_limit: 3000000,
    credit_days: 30,
    portal_token: "tcs-c4z1m",
    outstanding_balance: 612000,
    total_requests: 89,
  },
  {
    id: "c4",
    agency_id: "ag1",
    company_name: "HDFC Bank",
    contact_name: "Vikram Sinha",
    contact_email: "v.sinha@hdfcbank.com",
    contact_phone: "+91 98800 33333",
    credit_limit: 800000,
    credit_days: 15,
    portal_token: "hdfc-d9w5n",
    outstanding_balance: 48000,
    total_requests: 18,
  },
  {
    id: "c5",
    agency_id: "ag1",
    company_name: "Reliance Industries",
    contact_name: "Anita Joshi",
    contact_email: "a.joshi@ril.com",
    contact_phone: "+91 98700 44444",
    credit_limit: 5000000,
    credit_days: 60,
    portal_token: "ril-e6v8p",
    outstanding_balance: 0,
    total_requests: 12,
  },
];

const sampleOptions: RequestOption[] = [
  {
    id: "opt1",
    request_id: "r1",
    option_number: 1,
    type: "flight",
    provider: "IndiGo",
    supplier_system: "Travel Boutique Online",
    description: "IndiGo 6E-204 | BOM → DEL | 06:00 – 08:10",
    details: {
      flight_number: "6E-204",
      departure: "06:00",
      arrival: "08:10",
      duration: "2h 10m",
      class: "Economy",
      stops: "Non-stop",
      baggage: "15kg",
    },
    supplier_cost: 6800,
    client_price: 7480,
    margin: 680,
    status: "proposed",
    is_recommended: true,
  },
  {
    id: "opt2",
    request_id: "r1",
    option_number: 2,
    type: "flight",
    provider: "Air India",
    supplier_system: "Travel Boutique Online",
    description: "Air India AI-131 | BOM → DEL | 08:30 – 10:45",
    details: {
      flight_number: "AI-131",
      departure: "08:30",
      arrival: "10:45",
      duration: "2h 15m",
      class: "Economy",
      stops: "Non-stop",
      baggage: "25kg",
    },
    supplier_cost: 8200,
    client_price: 9020,
    margin: 820,
    status: "proposed",
    is_recommended: false,
  },
  {
    id: "opt3",
    request_id: "r1",
    option_number: 3,
    type: "hotel",
    provider: "Taj Mahal Hotel, New Delhi",
    supplier_system: "Direct Partner",
    description: "Taj Mahal New Delhi | Superior Room | 2 Nights",
    details: {
      room_type: "Superior Room",
      check_in: "2026-08-10",
      check_out: "2026-08-12",
      nights: 2,
      breakfast: "Included",
      cancellation: "Free until 48hrs",
    },
    supplier_cost: 14000,
    client_price: 15400,
    margin: 1400,
    status: "proposed",
    is_recommended: true,
  },
];

const sampleMessages: RequestMessage[] = [
  {
    id: "m1",
    request_id: "r1",
    sender_type: "client",
    sender_name: "Kavitha Reddy",
    message:
      "Hi, we need to send our VP Engineering to Delhi for a board meeting on Aug 10-12. Early morning flight preferred. Please include hotel options near Connaught Place.",
    created_at: "2026-08-05T09:15:00Z",
  },
  {
    id: "m2",
    request_id: "r1",
    sender_type: "agency",
    sender_name: "Arjun Mehta",
    message:
      "Understood, Kavitha. I've curated 2 flight options and a hotel recommendation. Option 1 (IndiGo) is the best value and arrives by 8:10 AM giving plenty of time before meetings. The Taj is near CP and our preferred partner so rates are excellent. Let me know if you'd like any alternatives.",
    created_at: "2026-08-05T11:30:00Z",
  },
];

export const mockRequests: TravelRequest[] = [
  {
    id: "r1",
    agency_id: "ag1",
    client_id: "c1",
    client: mockClients[0],
    request_number: "REQ-2026-0847",
    status: "options_shared",
    traveler_name: "Vikram Anand",
    traveler_email: "v.anand@infosys.com",
    trip_type: "combined",
    origin: "Mumbai",
    destination: "New Delhi",
    departure_date: "2026-08-10",
    return_date: "2026-08-12",
    purpose: "Board Meeting",
    budget: 25000,
    preferred_class: "Economy",
    special_instructions: "Window seat preferred. Veg meal.",
    assigned_to: "u2",
    assignee: mockUsers[1],
    submitted_at: "2026-08-05T09:15:00Z",
    due_at: "2026-08-07T18:00:00Z",
    options: sampleOptions,
    messages: sampleMessages,
  },
  {
    id: "r2",
    agency_id: "ag1",
    client_id: "c3",
    client: mockClients[2],
    request_number: "REQ-2026-0846",
    status: "pending",
    traveler_name: "Rohit Sharma",
    traveler_email: "r.sharma@tcs.com",
    trip_type: "flight",
    origin: "Bangalore",
    destination: "Singapore",
    departure_date: "2026-08-15",
    return_date: "2026-08-19",
    purpose: "Client Presentation",
    budget: 80000,
    preferred_class: "Business",
    assigned_to: "u3",
    assignee: mockUsers[2],
    submitted_at: "2026-08-05T07:42:00Z",
    due_at: "2026-08-06T18:00:00Z",
  },
  {
    id: "r3",
    agency_id: "ag1",
    client_id: "c2",
    client: mockClients[1],
    request_number: "REQ-2026-0845",
    status: "approved",
    traveler_name: "Preethi Krishnan",
    traveler_email: "p.krishnan@wipro.com",
    trip_type: "train",
    origin: "Chennai",
    destination: "Hyderabad",
    departure_date: "2026-08-08",
    purpose: "Internal Review",
    budget: 5000,
    assigned_to: "u2",
    assignee: mockUsers[1],
    submitted_at: "2026-08-04T14:20:00Z",
    approved_at: "2026-08-05T10:00:00Z",
  },
  {
    id: "r4",
    agency_id: "ag1",
    client_id: "c4",
    client: mockClients[3],
    request_number: "REQ-2026-0844",
    status: "booked",
    traveler_name: "Suresh Kumar",
    traveler_email: "s.kumar@hdfcbank.com",
    trip_type: "flight",
    origin: "Delhi",
    destination: "London",
    departure_date: "2026-08-20",
    return_date: "2026-08-27",
    purpose: "Annual Conference",
    budget: 150000,
    preferred_class: "Business",
    assigned_to: "u2",
    assignee: mockUsers[1],
    submitted_at: "2026-08-01T11:00:00Z",
    approved_at: "2026-08-03T09:00:00Z",
  },
  {
    id: "r5",
    agency_id: "ag1",
    client_id: "c1",
    client: mockClients[0],
    request_number: "REQ-2026-0843",
    status: "in_review",
    traveler_name: "Ananya Patel",
    traveler_email: "a.patel@infosys.com",
    trip_type: "visa",
    origin: "Pune",
    destination: "USA",
    departure_date: "2026-09-01",
    purpose: "Project Onsite",
    budget: 20000,
    special_instructions: "B1/B2 visa. Traveling for 3 months.",
    assigned_to: "u3",
    assignee: mockUsers[2],
    submitted_at: "2026-08-04T16:00:00Z",
    due_at: "2026-08-10T18:00:00Z",
  },
  {
    id: "r6",
    agency_id: "ag1",
    client_id: "c3",
    client: mockClients[2],
    request_number: "REQ-2026-0842",
    status: "completed",
    traveler_name: "Kiran Rao",
    traveler_email: "k.rao@tcs.com",
    trip_type: "combined",
    origin: "Mumbai",
    destination: "Dubai",
    departure_date: "2026-07-25",
    return_date: "2026-07-28",
    purpose: "Partner Meeting",
    budget: 60000,
    assigned_to: "u2",
    assignee: mockUsers[1],
    submitted_at: "2026-07-18T10:00:00Z",
    approved_at: "2026-07-20T09:00:00Z",
  },
];

export const mockBookings: Booking[] = [
  {
    id: "b1",
    agency_id: "ag1",
    request_id: "r4",
    request: mockRequests[3],
    booking_number: "BKG-2026-0412",
    supplier_system: "British Airways Portal",
    supplier_ref: "BA-7X9K2",
    supplier_cost: 120000,
    client_price: 132000,
    margin: 12000,
    status: "issued",
    supplier_paid: true,
    supplier_paid_at: "2026-08-03T14:00:00Z",
    supplier_paid_amount: 120000,
    client_invoiced: true,
    client_paid: false,
    created_at: "2026-08-03T12:00:00Z",
  },
  {
    id: "b2",
    agency_id: "ag1",
    request_id: "r6",
    request: mockRequests[5],
    booking_number: "BKG-2026-0408",
    supplier_system: "Travel Boutique Online",
    supplier_ref: "TBO-4Y1L9",
    supplier_cost: 45000,
    client_price: 49500,
    margin: 4500,
    status: "completed",
    supplier_paid: true,
    supplier_paid_at: "2026-07-20T15:00:00Z",
    supplier_paid_amount: 45000,
    client_invoiced: true,
    client_paid: true,
    client_paid_at: "2026-08-04T11:00:00Z",
    created_at: "2026-07-20T12:00:00Z",
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: "inv1",
    agency_id: "ag1",
    client_id: "c1",
    client: mockClients[0],
    invoice_number: "INV-2026-0231",
    amount: 385000,
    tax_amount: 69300,
    total_amount: 454300,
    status: "overdue",
    issued_date: "2026-07-01",
    due_date: "2026-07-31",
    paid_amount: 0,
    notes: "July travel services — 12 bookings",
  },
  {
    id: "inv2",
    agency_id: "ag1",
    client_id: "c3",
    client: mockClients[2],
    invoice_number: "INV-2026-0230",
    amount: 612000,
    tax_amount: 110160,
    total_amount: 722160,
    status: "sent",
    issued_date: "2026-08-01",
    due_date: "2026-08-31",
    paid_amount: 0,
    notes: "August travel services — 18 bookings",
  },
  {
    id: "inv3",
    agency_id: "ag1",
    client_id: "c2",
    client: mockClients[1],
    invoice_number: "INV-2026-0229",
    amount: 127500,
    tax_amount: 22950,
    total_amount: 150450,
    status: "partial",
    issued_date: "2026-07-15",
    due_date: "2026-08-29",
    paid_amount: 75000,
    notes: "July – August travel services",
  },
  {
    id: "inv4",
    agency_id: "ag1",
    client_id: "c4",
    client: mockClients[3],
    invoice_number: "INV-2026-0228",
    amount: 132000,
    tax_amount: 23760,
    total_amount: 155760,
    status: "sent",
    issued_date: "2026-08-03",
    due_date: "2026-08-18",
    paid_amount: 0,
  },
  {
    id: "inv5",
    agency_id: "ag1",
    client_id: "c3",
    client: mockClients[2],
    invoice_number: "INV-2026-0225",
    amount: 49500,
    tax_amount: 8910,
    total_amount: 58410,
    status: "paid",
    issued_date: "2026-07-25",
    due_date: "2026-08-24",
    paid_amount: 58410,
  },
];

export const mockSuppliers: Supplier[] = [
  {
    id: "s1",
    agency_id: "ag1",
    name: "Travel Boutique Online",
    type: "GDS / Flights + Hotels",
    contact_name: "Ravi Kumar",
    contact_email: "ravi@tbo.in",
    portal_url: "https://www.travelboutiqueonline.com",
    credit_balance: 85000,
  },
  {
    id: "s2",
    agency_id: "ag1",
    name: "IRCTC",
    type: "Rail",
    contact_email: "support@irctc.co.in",
    portal_url: "https://www.irctc.co.in",
    credit_balance: 12000,
  },
  {
    id: "s3",
    agency_id: "ag1",
    name: "British Airways",
    type: "Airline",
    contact_name: "BA Trade Desk",
    portal_url: "https://www.ba.com/agents",
    credit_balance: 0,
  },
  {
    id: "s4",
    agency_id: "ag1",
    name: "Taj Hotels",
    type: "Hotel Partner",
    contact_name: "Partnerships Team",
    contact_email: "corporate@tajhotels.com",
    credit_balance: 45000,
  },
  {
    id: "s5",
    agency_id: "ag1",
    name: "VFS Global",
    type: "Visa Services",
    contact_email: "india@vfsglobal.com",
    portal_url: "https://www.vfsglobal.com",
    credit_balance: 8000,
  },
];

export const dashboardMetrics = {
  activeRequests: 5,
  pendingApprovals: 2,
  bookingsThisMonth: 14,
  totalRevenue: 284500,
  outstandingReceivables: 1172510,
  supplierPayablesDue: 165000,
  overdueInvoices: 1,
  avgResponseTime: "4.2h",
};
